import * as fs from 'fs'

const STARTER_YAML = `# dokku-compose.yml — generated by dokku-compose init
plugins:
  postgres:
    url: https://github.com/dokku/dokku-postgres.git

services:
  myapp-postgres:
    plugin: postgres

apps:
  myapp:
    ports:
      - "http:80:3000"
    links:
      - myapp-postgres
    env:
      NODE_ENV: production
`

export function runInit(filePath: string, _apps: string[]): void {
  if (fs.existsSync(filePath)) {
    console.error(`File already exists: ${filePath}`)
    process.exit(1)
  }
  fs.writeFileSync(filePath, STARTER_YAML)
  console.log(`Created ${filePath}`)
}
